/* Statische data: vertalingen (nl/fr), standaard RAL-kleuren en RAL-woordenlijst. */
(() => {
  'use strict';

  /** UI-vertalingen per taal; sleutels komen overeen met data-i18n / data-i18n-placeholder in index.html. */
  Mesure.translations = {
    nl: {
      lbl_security: "Security",
      lbl_glastype: "Glastype",
      lbl_glastype_r: "Glastype (R)",
      lbl_glascode: "Bestaande glascode",
      lbl_glascode_r: "Bestaande glascode (R)",
      ph_glascode: "bv. 44.2 / 10 / 6",
      opt_kies_glas: "Kies glastype...",
      glass_float: "Float helder",
      glass_tempered: "Gehard veiligheidsglas",
      glass_laminated: "Gelaagd veiligheidsglas",
      glass_double: "Isolatieglas dubbel",
      glass_triple: "Isolatieglas triple",
      glass_lowe: "Low-E isolatieglas",
      glass_acoustic: "Akoestisch gelaagd glas",
      glass_fire: "Brandwerend glas",
      glass_wired: "Draadglas",
      glass_frosted: "Mat / gezuurd glas",
      glass_tinted: "Getint / zonwerend glas",
      glass_other: "Ander",
      nav_clear: "Wis Alles",
      nav_print: "Print PDF",
      print_title: "Dormakaba Opmetingsblad",
      print_subtitle: "Vervanging / Nieuwe Installatie",
      hdr_dossier: "Dossier & Klant",
      lbl_werf: "Werf / Chantier",
      ph_werf: "Naam werf",
      lbl_datum: "Datum opm.",
      lbl_dossier: "Dossiernr.",
      ph_dossier: "bv. 12345",
      lbl_contact: "Contactpersoon",
      ph_naam: "Naam",
      lbl_telefoon: "Telefoon",
      lbl_locatie: "Locatie",
      ph_locatie: "Straat + Gem.",
      lbl_deurlocatie: "Deurlocatie (Gebouw)",
      ph_deurlocatie: "bv. Hoofdingang, Gang 2",
      hdr_schets: "Schets / Technische Visualisation (Live)",
      btn_reset: "↺ Reset Velden",
      hdr_vervangen: "Wat wordt vervangen?",
      opt_aandrijving: "Aandrijfsysteem",
      opt_zonder_kap: "└ Zonder Kap",
      lbl_oud_systeem: "Oud Systeem (Bestaand)",
      ph_oud_systeem: "bv. Oude Besam / Dorma ...",
      opt_vleugel_l: "Linker vleugel",
      opt_vleugel_r: "Rechter vleugel",
      opt_beide_vleugels: "Beide vleugels",
      opt_vast_l: "Vast paneel links",
      opt_vast_r: "Vast paneel rechts",
      opt_beide_vast: "Beide vaste panelen",
      hdr_config: "Systeem Configuratie",
      lbl_deurtype: "Deurtype",
      lbl_draaideur_uitrusting: "Draaideur Uitrusting & Arm",
      lbl_armsoort: "Armsoort",
      lbl_asmaat: "Asmaat / Diepte",
      lbl_muur_deur_diepte: "Diepte tussen muur en deurvlak",
      lbl_profiel: "Profielsysteem",
      opt_kies_profiel: "Kies profiel/type...",
      opt_ander: "Ander / Zonder",
      lbl_aandrijving: "Nieuwe Aandrijving",
      opt_kies_model: "Kies model...",
      lbl_openingswijze: "Openingswijze",
      lbl_koord: "Koordophanging systeem",
      opt_nee: "Nee",
      opt_ja: "Ja",
      lbl_ral: "RAL Kleur / Finish",
      ph_ral: "bv. RAL 7016 of Anodisé",
      hdr_globale_afm: "Globale Afmetingen (mm)",
      lbl_tb: "Totaal Breedte (TB)",
      lbl_th: "Totaal Hoogte (TH)",
      lbl_lb: "Loopbreedte (LB)",
      lbl_lh: "Loophoogte (LH)",
      lbl_kap_h: "Kap Hoogte",
      lbl_kap_d: "Kap Diepte",
      hdr_panelen: "Schuifpaneel & Vaste Panelen",
      lbl_glaslat: "Glaslatten Dikte",
      lbl_glasmaat: "Glasmaat (tot glaslatten)",
      lbl_prof_boven: "Profieldikte Boven",
      lbl_prof_onder: "Profieldikte Onder",
      lbl_prof_sluit: "Profieldikte Sluitkant",
      lbl_prof_open: "Profieldikte Openingskant",
      lbl_glaslat_r: "Glaslatten Dikte (R)",
      lbl_glasmaat_r: "Glasmaat (R)",
      lbl_vp_l: "Vast Paneel Links (VP L)",
      lbl_b_vpl: "Breedte (VP L)",
      ph_vp_breedte: "mm (0 = geen)",
      lbl_h_vpl: "Hoogte (VP L)",
      lbl_vp_r: "Vast Paneel Rechts (VP R)",
      lbl_b_vpr: "Breedte (VP R)",
      lbl_h_vpr: "Hoogte (VP R)",
      hdr_opties: "Onderdelen & Opties",
      lbl_vloergeleider: "Vloergeleider Type",
      opt_zonder: "Zonder",
      lbl_montageplaat: "Alu-montageplaat",
      hint_montageplaat: "Montage plaatjes voor glijarm-rail of duwarm niet vergeten!",
      lbl_slot: "Slotmechanisme",
      opt_geen_slot: "Geen slot",
      opt_vloer_sluit: "Vloerslot: Aan Sluitkant",
      opt_vloer_centraal: "Vloerslot: Centraal (Midden)",
      opt_haakslot: "Haakslot (Profiel)",
      lbl_pos_vloerslot: "Positie & Uitvoering Vloerslot",
      lbl_type_uitv: "Type uitvoering:",
      opt_half: "Half",
      opt_doorlopend: "Doorlopend",
      lbl_offset: "Offset vanaf sluitkant (mm):",
      lbl_boring: "Vloerboring uit te voeren",
      hdr_tech: "Technieker & Extra",
      lbl_tech_naam: "Naam Technieker",
      ph_tech_naam: "Jouw naam",
      lbl_opm: "Opmerkingen",
      ph_opm: "Eventuele opmerkingen of speciale vereisten...",
      btn_gen_pdf: "Genereer PDF / Print"
    },
    fr: {
      lbl_security: "Sécurité",
      lbl_glastype: "Type de verre",
      lbl_glastype_r: "Type de verre (D)",
      lbl_glascode: "Code du vitrage existant",
      lbl_glascode_r: "Code du vitrage existant (D)",
      ph_glascode: "ex. 44.2 / 10 / 6",
      opt_kies_glas: "Choisir le type de verre...",
      glass_float: "Verre float clair",
      glass_tempered: "Verre de sécurité trempé",
      glass_laminated: "Verre de sécurité feuilleté",
      glass_double: "Double vitrage isolant",
      glass_triple: "Triple vitrage isolant",
      glass_lowe: "Vitrage isolant Low-E",
      glass_acoustic: "Verre feuilleté acoustique",
      glass_fire: "Verre résistant au feu",
      glass_wired: "Verre armé",
      glass_frosted: "Verre mat / dépoli",
      glass_tinted: "Verre teinté / contrôle solaire",
      glass_other: "Autre",
      nav_clear: "Tout Effacer",
      nav_print: "Imprimer PDF",
      print_title: "Fiche de Mesure Dormakaba",
      print_subtitle: "Remplacement / Nouvelle Installation",
      hdr_dossier: "Dossier & Client",
      lbl_werf: "Chantier",
      ph_werf: "Nom du chantier",
      lbl_datum: "Date de mesur.",
      lbl_dossier: "N° Dossier",
      ph_dossier: "ex. 12345",
      lbl_contact: "Personne de contact",
      ph_naam: "Nom",
      lbl_telefoon: "Téléphone",
      lbl_locatie: "Emplacement",
      ph_locatie: "Rue + Commune",
      lbl_deurlocatie: "Emplacement porte",
      ph_deurlocatie: "ex. Entrée principale",
      hdr_schets: "Croquis / Visuel Technique (Live)",
      btn_reset: "↺ Réinitialiser",
      hdr_vervangen: "Qu'est-ce qui est remplacé ?",
      opt_aandrijving: "Système d'entraînement",
      opt_zonder_kap: "└ Sans capot",
      lbl_oud_systeem: "Ancien système (Existant)",
      ph_oud_systeem: "ex. Ancien Besam / Dorma ...",
      opt_vleugel_l: "Vantail gauche",
      opt_vleugel_r: "Vantail droit",
      opt_beide_vleugels: "Deux vantaux",
      opt_vast_l: "Panneau fixe gauche",
      opt_vast_r: "Panneau fixe droit",
      opt_beide_vast: "Deux panneaux fixes",
      hdr_config: "Configuration du Système",
      lbl_deurtype: "Type de porte",
      lbl_draaideur_uitrusting: "Équipement & Bras Porte Battante",
      lbl_armsoort: "Type de bras",
      lbl_asmaat: "Mesure d'axe / Profondeur",
      lbl_muur_deur_diepte: "Profondeur entre mur et porte",
      lbl_profiel: "Système de profilés",
      opt_kies_profiel: "Choisir profil...",
      opt_ander: "Autre / Sans",
      lbl_aandrijving: "Nouvel Opérateur",
      opt_kies_model: "Choisir modèle...",
      lbl_openingswijze: "Sens d'ouverture",
      lbl_koord: "Système de suspension à corde",
      opt_nee: "Non",
      opt_ja: "Oui",
      lbl_ral: "Couleur RAL / Finition",
      ph_ral: "ex. RAL 7016 ou Anodisé",
      hdr_globale_afm: "Dimensions Globales (mm)",
      lbl_tb: "Largeur Totale (LT)",
      lbl_th: "Hauteur Totale (HT)",
      lbl_lb: "Largeur de passage (LP)",
      lbl_lh: "Hauteur de passage (HP)",
      lbl_kap_h: "Hauteur capot",
      lbl_kap_d: "Profondeur capot",
      hdr_panelen: "Panneau Coulissant & Panneaux Fixes",
      lbl_glaslat: "Épaisseur parcloses",
      lbl_glasmaat: "Mesure de verre (jusqu'aux parcloses)",
      lbl_prof_boven: "Épaisseur profilé Haut",
      lbl_prof_onder: "Épaisseur profilé Bas",
      lbl_prof_sluit: "Épaisseur profilé côté fermeture",
      lbl_prof_open: "Épaisseur profilé côté ouverture",
      lbl_glaslat_r: "Épaisseur parcloses (D)",
      lbl_glasmaat_r: "Mesure de verre (D)",
      lbl_vp_l: "Panneau Fixe Gauche (PF G)",
      lbl_b_vpl: "Largeur (PF G)",
      ph_vp_breedte: "mm (0 = aucun)",
      lbl_h_vpl: "Hauteur (PF G)",
      lbl_vp_r: "Panneau Fixe Droit (PF D)",
      lbl_b_vpr: "Largeur (PF D)",
      lbl_h_vpr: "Hauteur (PF D)",
      hdr_opties: "Composants & Options",
      lbl_vloergeleider: "Type guide au sol",
      opt_zonder: "Sans",
      lbl_montageplaat: "Plaque de montage alu",
      hint_montageplaat: "N'oubliez pas les plaquettes de montage pour le rail à bras glissant ou le bras compas !",
      lbl_slot: "Mécanisme de verrouillage",
      opt_geen_slot: "Pas de serrure",
      opt_vloer_sluit: "Verrou au sol: Côté Fermeture",
      opt_vloer_centraal: "Verrou au sol: Central (Milieu)",
      opt_haakslot: "Serrure à crochet (Profilé)",
      lbl_pos_vloerslot: "Position & Exécution verrou au sol",
      lbl_type_uitv: "Type d'exécution:",
      opt_half: "Demi",
      opt_doorlopend: "Continu",
      lbl_offset: "Décalage côté fermeture (mm):",
      lbl_boring: "Forage au sol à effectuer",
      hdr_tech: "Technicien & Extra",
      lbl_tech_naam: "Nom du technicien",
      ph_tech_naam: "Votre nom",
      lbl_opm: "Remarques",
      ph_opm: "Remarques éventuelles ou exigences spéciales...",
      btn_gen_pdf: "Générer PDF / Imprimer"
    }
  };

  /** Basis-RAL-kleuren (fallback als de volledige palette-gist niet geladen kan worden). */
  Mesure.baseRals = [
    { ral: "RAL 1013", hex: "#E3D9C6", label: "Parelwit", keywords: "wit parelwit beige blanc 1013" },
    { ral: "RAL 3020", hex: "#CC0605", label: "Verkeersrood", keywords: "rood red rouge brandweerrood 3020" },
    { ral: "RAL 5010", hex: "#0E46A3", label: "Gentiaanblauw", keywords: "blauw blue bleu gentiaanblauw 5010" },
    { ral: "RAL 7016", hex: "#383E42", label: "Antracietgrijs", keywords: "antraciet grijs gris grey 7016" },
    { ral: "RAL 9005", hex: "#1A1A1A", label: "Gitzwart", keywords: "zwart black noir 9005" },
    { ral: "RAL 9006", hex: "#A5A8A6", label: "Blank aluminium", keywords: "zilver silver argent blank anodisé anodise ano natuur 9006" },
    { ral: "RAL 9010", hex: "#FFFFFF", label: "Zuiver wit", keywords: "wit zuiverwit blanc 9010" },
    { ral: "RAL 9016", hex: "#F4F8F4", label: "Verkeerswit", keywords: "wit white blanc verkeerswit 9016" }
  ];

  /** RAL-kleuren die zonder zoekterm als snelkeuze getoond worden. */
  Mesure.defaultRals = ["RAL 9016", "RAL 9005", "RAL 7016", "RAL 9006", "RAL 3020", "RAL 5010"];

  /** Engelse RAL-kleurnamen -> nl/fr (langste sleutel eerst toegepast, zie ral.js). */
  Mesure.ralLexicon = {
    nl: {
      "green beige": "groenbeige",
      "sand yellow": "zandgeel",
      "signal yellow": "signaalgeel",
      "golden yellow": "goudgeel",
      "honey yellow": "honinggeel",
      "maize yellow": "maisgeel",
      "daffodil yellow": "narcissengeel",
      "brown beige": "bruinbeige",
      "lemon yellow": "citroengeel",
      "oyster white": "parelwit",
      "light ivory": "licht ivoor",
      "sulfur yellow": "zwavelgeel",
      "saffron yellow": "saffraangeel",
      "zinc yellow": "zinkgeel",
      "grey beige": "grijsbeige",
      "olive yellow": "olijfgeel",
      "traffic yellow": "verkeersgeel",
      "traffic orange": "verkeersoranje",
      "traffic red": "verkeersrood",
      "traffic blue": "verkeersblauw",
      "traffic green": "verkeersgroen",
      "traffic grey": "verkeersgrijs",
      "traffic white": "verkeerswit",
      "pure white": "zuiver wit",
      "jet black": "gitzwart",
      "anthracite grey": "antracietgrijs",
      "light grey": "lichtgrijs",
      "dark grey": "donkergrijs",
      "silver grey": "zilvergrijs",
      "blue grey": "blauwgrijs",
      "green grey": "groengrijs",
      "brown grey": "bruingrijs",
      "yellow grey": "geelgrijs",
      "black grey": "zwartgrijs",
      "white aluminium": "blank aluminiumkleurig",
      "grey aluminium": "grijs aluminiumkleurig",
      "flame red": "vuurrood",
      "ruby red": "robijnrood",
      "wine red": "wijnrood",
      "moss green": "mosgroen",
      "leaf green": "bladgroen",
      "cobalt blue": "kobaltblauw",
      "sky blue": "hemelsblauw",
      "ultramarine blue": "ultramarijnblauw",
      "chocolate brown": "chocoladebruin",
      cream: "cremewit",
      ivory: "ivoor",
      beige: "beige",
      yellow: "geel",
      orange: "oranje",
      red: "rood",
      violet: "violet",
      blue: "blauw",
      green: "groen",
      grey: "grijs",
      gray: "grijs",
      brown: "bruin",
      white: "wit",
      black: "zwart",
      light: "licht",
      dark: "donker",
      pale: "bleek",
      pastel: "pastel",
      pearl: "parel",
      brilliant: "briljant",
      signal: "signaal",
      olive: "olijf"
    },
    fr: {
      "green beige": "beige vert",
      "sand yellow": "jaune sable",
      "signal yellow": "jaune de securite",
      "golden yellow": "jaune or",
      "honey yellow": "jaune miel",
      "maize yellow": "jaune mais",
      "daffodil yellow": "jaune narcisse",
      "brown beige": "beige brun",
      "lemon yellow": "jaune citron",
      "oyster white": "blanc perle",
      "light ivory": "ivoire clair",
      "sulfur yellow": "jaune soufre",
      "saffron yellow": "jaune safran",
      "zinc yellow": "jaune zinc",
      "grey beige": "beige gris",
      "olive yellow": "jaune olive",
      "traffic yellow": "jaune signalisation",
      "traffic orange": "orange signalisation",
      "traffic red": "rouge signalisation",
      "traffic blue": "bleu signalisation",
      "traffic green": "vert signalisation",
      "traffic grey": "gris signalisation",
      "traffic white": "blanc signalisation",
      "pure white": "blanc pur",
      "jet black": "noir fonce",
      "anthracite grey": "gris anthracite",
      "light grey": "gris clair",
      "dark grey": "gris fonce",
      "silver grey": "gris argent",
      "blue grey": "gris bleu",
      "green grey": "gris vert",
      "brown grey": "gris brun",
      "yellow grey": "gris jaune",
      "black grey": "gris noir",
      "white aluminium": "aluminium blanc",
      "grey aluminium": "aluminium gris",
      "flame red": "rouge feu",
      "ruby red": "rouge rubis",
      "wine red": "rouge vin",
      "moss green": "vert mousse",
      "leaf green": "vert feuillage",
      "cobalt blue": "bleu cobalt",
      "sky blue": "bleu ciel",
      "ultramarine blue": "bleu outremer",
      "chocolate brown": "brun chocolat",
      cream: "blanc creme",
      ivory: "ivoire",
      beige: "beige",
      yellow: "jaune",
      orange: "orange",
      red: "rouge",
      violet: "violet",
      blue: "bleu",
      green: "vert",
      grey: "gris",
      gray: "gris",
      brown: "brun",
      white: "blanc",
      black: "noir",
      light: "clair",
      dark: "fonce",
      pale: "pale",
      pastel: "pastel",
      pearl: "nacre",
      brilliant: "brillant",
      signal: "securite",
      olive: "olive"
    }
  };
})();
